variables:
  IGNORE_TF_DEPRECATION_WARNING: true
  TF_STATE_NAME: default

include:
  template: Terraform/Base.latest.gitlab-ci.yml

stages:
  - validate
  - build
  - deploy
  - cleanup

validate:
  extends: .terraform:validate

plan:
  extends: .terraform:build

apply:
  extends: .terraform:deploy

destroy:
  extends: .terraform:destroy