variables:
  IGNORE_TF_DEPRECATION_WARNING: true
  
include:
  template: Terraform/Base.latest.gitlab-ci.yml

stages:
  - validate
  - build
  - deploy
  - cleanup

# validate:
#   extends: .terraform:validate

db-plan:
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/db-infra
    TF_STATE_NAME: default
  extends: .terraform:build

lambda-plan:
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/user-rotation
    TF_STATE_NAME: default
  extends: .terraform:build

# apply:
#   extends: .terraform:deploy

# destroy:
#   extends: .terraform:destroy