CREATE TABLE IF NOT EXISTS animals (
  id BIGSERIAL PRIMARY KEY,
  name TEXT,
  type VARCHAR(255) NOT NULL,  -- Matches @Enumerated(EnumType.STRING)
  description TEXT,
  birthdate TIMESTAMP  -- Matches Date type in JPA
);

INSERT INTO animals (birthdate, description, name, type) VALUES ('2022-10-11 17:43:55', 'A playful and energetic companion.', 'Ellie', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2015-03-16 07:07:01', 'Loves long walks and enjoys fetching balls.', 'Max', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-06-03 22:03:50', 'Loves long walks and enjoys fetching balls.', 'Milo', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2023-02-10 09:43:39', 'Has a vibrant personality and loves attention.', 'Rex', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2017-07-24 10:47:40', 'Enjoys climbing and perching on high places.', 'Bella', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-05-13 20:35:08', 'Strong and graceful, loves running in open fields.', 'Charlie', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-02-08 14:43:06', 'Loves long walks and enjoys fetching balls.', 'Ruby', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2020-01-04 13:44:31', 'Loves long walks and enjoys fetching balls.', 'Finn', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2015-03-28 14:56:50', 'Enjoys chirping in the morning and loves seeds.', 'Cooper', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-09-22 22:40:27', 'Enjoys chirping in the morning and loves seeds.', 'Milo', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-03-19 22:00:50', 'Known for its intelligence and loyalty.', 'Cooper', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-01-16 05:00:58', 'Has a vibrant personality and loves attention.', 'Rosie', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2023-12-10 04:18:42', 'Loves long walks and enjoys fetching balls.', 'Max', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2015-04-17 01:34:14', 'A playful and energetic companion.', 'Zoey', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-05-13 15:21:38', 'A playful and energetic companion.', 'Ellie', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2020-10-06 12:32:19', 'Strong and graceful, loves running in open fields.', 'Rex', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-05-29 15:44:14', 'A calm and affectionate pet with a soft coat.', 'Teddy', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2017-12-30 01:08:44', 'Loyal and protective, always by your side.', 'Rex', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-12-02 00:49:52', 'Loyal and protective, always by your side.', 'Teddy', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-04-07 20:11:39', 'Loyal and protective, always by your side.', 'Finn', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2023-07-03 13:24:28', 'Loyal and protective, always by your side.', 'Bella', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-05-03 09:23:53', 'A calm and affectionate pet with a soft coat.', 'Molly', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2022-06-27 14:07:20', 'A calm and affectionate pet with a soft coat.', 'Rex', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-09-23 16:09:56', 'Loves long walks and enjoys fetching balls.', 'Luna', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2022-11-19 05:14:22', 'Strong and graceful, loves running in open fields.', 'Rocky', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2022-04-06 06:00:08', 'A playful and energetic companion.', 'Ellie', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-09-16 18:29:51', 'Loves long walks and enjoys fetching balls.', 'Buddy', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-09-23 14:24:00', 'Strong and graceful, loves running in open fields.', 'Buddy', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-01-01 15:36:09', 'Enjoys chirping in the morning and loves seeds.', 'Oscar', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-11-18 04:19:11', 'Known for its intelligence and loyalty.', 'Ruby', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-08-20 03:55:11', 'Known for its intelligence and loyalty.', 'Finn', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-07-31 03:59:30', 'Has a vibrant personality and loves attention.', 'Oliver', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-07-20 00:14:02', 'Known for its intelligence and loyalty.', 'Rocky', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-10-04 04:51:05', 'A curious and gentle animal with soft fur.', 'Daisy', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-10-14 02:55:55', 'A curious and gentle animal with soft fur.', 'Peanut', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2023-10-31 07:44:34', 'Enjoys chirping in the morning and loves seeds.', 'Buster', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2023-08-02 23:01:32', 'A curious and gentle animal with soft fur.', 'Coco', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-06-01 09:58:17', 'Enjoys chirping in the morning and loves seeds.', 'Peanut', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2022-06-08 21:16:25', 'Strong and graceful, loves running in open fields.', 'Rocky', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-09-01 00:04:27', 'Loves long walks and enjoys fetching balls.', 'Sadie', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-04-15 22:46:12', 'Known for its intelligence and loyalty.', 'Rex', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-08-04 12:45:02', 'Has a vibrant personality and loves attention.', 'Zoey', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-08-31 15:26:42', 'Enjoys climbing and perching on high places.', 'Ruby', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-05-21 05:32:44', 'A playful and energetic companion.', 'Coco', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2017-05-18 01:49:04', 'A playful and energetic companion.', 'Rocky', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-01-04 17:59:24', 'A calm and affectionate pet with a soft coat.', 'Ruby', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-10-28 16:10:25', 'Strong and graceful, loves running in open fields.', 'Finn', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2020-06-07 06:13:44', 'Enjoys climbing and perching on high places.', 'Bailey', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-02-18 08:13:20', 'Loves long walks and enjoys fetching balls.', 'Molly', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-01-25 11:59:51', 'Enjoys climbing and perching on high places.', 'Max', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-06-27 05:02:15', 'Known for its intelligence and loyalty.', 'Luna', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-07-20 10:06:02', 'Known for its intelligence and loyalty.', 'Peanut', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2020-01-31 20:23:44', 'Loves long walks and enjoys fetching balls.', 'Ellie', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2017-11-30 11:07:06', 'A curious and gentle animal with soft fur.', 'Max', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-12-12 01:12:14', 'A curious and gentle animal with soft fur.', 'Buster', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2017-11-18 23:24:24', 'Has a vibrant personality and loves attention.', 'Ginger', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-10-21 00:23:31', 'Loyal and protective, always by your side.', 'Bella', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2015-02-11 19:12:14', 'Loves long walks and enjoys fetching balls.', 'Zoey', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2015-08-19 14:39:27', 'Strong and graceful, loves running in open fields.', 'Oscar', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-12-13 05:40:29', 'A playful and energetic companion.', 'Finn', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-09-22 09:37:12', 'Loves long walks and enjoys fetching balls.', 'Coco', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2017-06-03 16:20:48', 'Known for its intelligence and loyalty.', 'Zoey', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-04-06 19:20:53', 'Has a vibrant personality and loves attention.', 'Lucky', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2015-12-29 22:28:49', 'A playful and energetic companion.', 'Buster', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-01-23 21:15:30', 'Loves long walks and enjoys fetching balls.', 'Max', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2022-06-02 15:44:22', 'Known for its intelligence and loyalty.', 'Jack', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2015-09-25 05:50:56', 'Strong and graceful, loves running in open fields.', 'Coco', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-06-04 17:54:24', 'Enjoys climbing and perching on high places.', 'Ellie', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2022-05-29 21:16:17', 'A curious and gentle animal with soft fur.', 'Teddy', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-10-09 00:01:22', 'Enjoys climbing and perching on high places.', 'Lucky', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2023-05-21 08:01:01', 'Enjoys chirping in the morning and loves seeds.', 'Finn', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-02-25 09:18:06', 'Loves long walks and enjoys fetching balls.', 'Max', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-05-14 20:56:44', 'Known for its intelligence and loyalty.', 'Charlie', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-02-03 05:33:29', 'A calm and affectionate pet with a soft coat.', 'Luna', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-11-08 02:19:58', 'Enjoys chirping in the morning and loves seeds.', 'Charlie', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-09-08 18:43:26', 'A curious and gentle animal with soft fur.', 'Buddy', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-07-27 22:22:34', 'Has a vibrant personality and loves attention.', 'Toby', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2020-10-16 23:08:00', 'Enjoys climbing and perching on high places.', 'Teddy', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-09-29 19:51:55', 'A calm and affectionate pet with a soft coat.', 'Oliver', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2022-12-22 11:26:35', 'A playful and energetic companion.', 'Bailey', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-02-22 18:42:23', 'A curious and gentle animal with soft fur.', 'Zoey', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2023-05-18 19:28:12', 'Enjoys climbing and perching on high places.', 'Charlie', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-02-14 18:59:25', 'A curious and gentle animal with soft fur.', 'Cooper', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2022-11-20 02:52:57', 'Enjoys climbing and perching on high places.', 'Toby', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-11-15 21:40:28', 'Known for its intelligence and loyalty.', 'Ginger', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2020-05-29 05:48:04', 'Loves long walks and enjoys fetching balls.', 'Luna', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-10-31 08:36:44', 'Strong and graceful, loves running in open fields.', 'Charlie', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-04-08 23:50:18', 'A calm and affectionate pet with a soft coat.', 'Luna', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-10-18 17:09:22', 'Known for its intelligence and loyalty.', 'Luna', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2015-01-15 13:13:35', 'Loyal and protective, always by your side.', 'Daisy', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2023-09-03 14:16:31', 'Loyal and protective, always by your side.', 'Lucky', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-06-29 07:35:40', 'A calm and affectionate pet with a soft coat.', 'Lucky', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-03-17 03:05:53', 'Has a vibrant personality and loves attention.', 'Jack', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-03-30 15:00:51', 'Enjoys climbing and perching on high places.', 'Peanut', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2020-05-26 17:15:56', 'A playful and energetic companion.', 'Lola', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2023-11-22 19:35:03', 'A curious and gentle animal with soft fur.', 'Lola', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2020-02-13 13:15:07', 'Enjoys chirping in the morning and loves seeds.', 'Max', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2021-07-23 03:48:13', 'A playful and energetic companion.', 'Daisy', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-05-14 13:08:30', 'A calm and affectionate pet with a soft coat.', 'Cooper', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2015-07-29 04:38:38', 'Known for its intelligence and loyalty.', 'Finn', 'DOG');